-- Author: Ozy

-- One line per entry: "spellID,category,phrase"
-- Categories: neutral|snarky|spicy (or n|s|sp)
-- You can add as many lines as you like. These load every login/reload.

OZY_MAGE_LINES_VERSION = 1
OZY_MAGE_LINES = OZY_MAGE_LINES or {
  -- Arcane Intellect (1459) – 25 neutral, 25 snarky, 25 spicy
  "1459,neutral,%s for %t. Brain cache warmed.",
  "1459,neutral,Installing extra RAM via %s on %t.",
  "1459,neutral,%t receives %s. Synapses online.",
  "1459,neutral,%s applied to %t. Thoughts accelerate.",
  "1459,neutral,%t, enjoy %s—ideas may appear unannounced.",
  "1459,neutral,%s uplink for %t. Latency reduced.",
  "1459,neutral,%s on %t. Creativity buffed.",
  "1459,neutral,%t updated with %s. Brain overclocked.",
  "1459,neutral,%s primed. %t’s synapses hum.",
  "1459,neutral,%s linked. %t’s mind expands.",
  "1459,neutral,%s established. %t’s clarity increases.",
  "1459,neutral,%s tuned. %t’s focus sharpens.",
  "1459,neutral,%s initialized on %t. Boot sequence complete.",
  "1459,neutral,%s granted. %t gains insight.",
  "1459,neutral,%s synchronized. %t’s cortex cheers.",
  "1459,neutral,%s handshake with %t. Bandwidth improved.",
  "1459,neutral,%s loaded. %t’s headspace optimized.",
  "1459,neutral,%s activated. %t’s neurons applaud.",
  "1459,neutral,%s calibrated. %t processes faster.",
  "1459,neutral,%s deployed for %t. Brainwaves align.",
  "1459,neutral,%s engaged. %t’s ideas get crisp.",
  "1459,neutral,%s seal of brilliance on %t.",
  "1459,neutral,%s uplifts %t’s cognition.",
  "1459,neutral,%s: mental throughput up for %t.",
  "1459,neutral,%s on %t. Genius pending.",

  "1459,snarky,%t, your brain needs help; have %s.",
  "1459,snarky,%s for %t. Maybe read the boss page this time.",
  "1459,snarky,%t + %s = fewer oopsies (theoretically).",
  "1459,snarky,%s loaded. Patch notes: brain supports multi-threading, %t.",
  "1459,snarky,%t, %s won’t fix tunnel vision—but it tries.",
  "1459,snarky,%s applied. Try thinking before pulling, %t.",
  "1459,snarky,%t, %s should help you find your keybinds.",
  "1459,snarky,%s engaged. Please locate your feet, %t.",
  "1459,snarky,%t, %s—because asking chat isn’t a rotation.",
  "1459,snarky,%s online. If wipes continue, it’s not the buff, %t.",
  "1459,snarky,%t, %s won’t loot for you, but it can’t hurt.",
  "1459,snarky,%s for %t. Skill still required.",
  "1459,snarky,%t, %s may enable reading nameplates.",
  "1459,snarky,%s equipped. Tutorial mode off, %t.",
  "1459,snarky,%t, %s installed. Use responsibly.",
  "1459,snarky,%s injected. Patch your gameplay next, %t.",
  "1459,snarky,%t, %s—now with 20% fewer wrong targets.",
  "1459,snarky,%s activated. Don’t outsmart the tank, %t.",
  "1459,snarky,%t, %s is not a taunt.",
  "1459,snarky,%s uploaded. Try a two-button rotation, %t.",
  "1459,snarky,%t, %s can’t save you from lava.",
  "1459,snarky,%s: fewer questions, more actions, %t.",
  "1459,snarky,%t, %s installed. Reading is OP.",
  "1459,snarky,%s primed. Remember to buff others too, %t.",
  "1459,snarky,%t, %s won’t fix key turning.",

  "1459,spicy,%t, %s engaged. IQ unlocked.",
  "1459,spicy,%s: brain overdrive for %t. Handle with care.",
  "1459,spicy,%s on %t. Brainwaves amplified.",
  "1459,spicy,%t supercharged with %s. Creative chaos pending.",
  "1459,spicy,%s delivered. Enlightenment DLC installed for %t.",
  "1459,spicy,%s beams into %t. Synaptic fireworks.",
  "1459,spicy,%s floods %t. Thoughts go supersonic.",
  "1459,spicy,%t modded with %s. Warranty void maybe.",
  "1459,spicy,%s on %t. Ideas unlocked; brakes optional.",
  "1459,spicy,%t ascends via %s. Use for good.",
  "1459,spicy,%s invoked. %t’s cortex hits overdrive.",
  "1459,spicy,%s on %t. Genius turbo.",
  "1459,spicy,%t upgraded with %s. Brain go brr.",
  "1459,spicy,%s fired. %t’s neurons throw a party.",
  "1459,spicy,%t drinks %s. Overflow imminent.",
  "1459,spicy,%s uploads brilliance to %t in 3…2…1.",
  "1459,spicy,%s detonates on %t. Big brain boom.",
  "1459,spicy,%t, %s awakened. Handle like nitro.",
  "1459,spicy,%s spins up. %t’s IQ fan screaming.",
  "1459,spicy,%t overclocks with %s. Hold my staff.",
  "1459,spicy,%s surge to %t. Think dangerously.",
  "1459,spicy,%t receives %s. Brain in the fast lane.",
  "1459,spicy,%s beams brilliance straight into %t.",
  "1459,spicy,%t unlocks big brain with %s.",

  -- Arcane Brilliance (23028) – 25 neutral, 25 snarky, 25 spicy
  "23028,neutral,%s online. Collective brainpower rising.",
  "23028,neutral,%s radiates through the group. Ideas propagate.",
  "23028,neutral,Group synchronized: %s deployed.",
  "23028,neutral,%s uplink: group cognition boosted.",
  "23028,neutral,%s pulses across the raid. Focus improves.",
  "23028,neutral,%s woven through the party. Clarity increases.",
  "23028,neutral,%s active. Brainstorm ready.",
  "23028,neutral,%s amplifies team insight.",
  "23028,neutral,%s stabilizes group thought bandwidth.",
  "23028,neutral,%s: group idea throughput up.",
  "23028,neutral,%s resonance lifts the raid’s IQ.",
  "23028,neutral,%s tuned. Shared understanding rises.",
  "23028,neutral,%s across the roster. Strategy sharpens.",
  "23028,neutral,%s boosts group concentration.",
  "23028,neutral,%s harmonizes our brains, probably.",
  "23028,neutral,%s installed across all heads present.",
  "23028,neutral,%s cadence steady. Meetings optional.",
  "23028,neutral,%s ensures fewer blank stares.",
  "23028,neutral,%s reduces raid-wide confusion.",
  "23028,neutral,%s: the meeting that could’ve been an aura.",
  "23028,neutral,%s links our minds for peak performance.",
  "23028,neutral,%s illuminates the raid. Figuratively.",
  "23028,neutral,%s network established. Sync complete.",
  "23028,neutral,%s lifts everyone’s mental ceiling.",
  "23028,neutral,%s blankets the group in brilliance.",

  "23028,snarky,%s applied. Big brain, same toes—watch them.",
  "23028,snarky,%s installed. If we wipe, it’s not the buff.",
  "23028,snarky,%s: please engage thinking before lever pulling.",
  "23028,snarky,%s online. Don’t outsmart the tank.",
  "23028,snarky,%s across the raid. Mechanics still exist.",
  "23028,snarky,%s here. Try not to facepull with confidence.",
  "23028,snarky,%s on group. Ignoring fire remains bad.",
  "23028,snarky,%s: now with 20% fewer ‘who pulled?’ moments.",
  "23028,snarky,%s tuning complete. DPS excuses not included.",
  "23028,snarky,%s humming. Blame reduction not guaranteed.",
  "23028,snarky,%s on raid. Please read your tooltips.",
  "23028,snarky,%s might help; standing in cleave won’t.",
  "23028,snarky,%s set. Try using keybinds, not hopes.",
  "23028,snarky,%s uploaded. Meeting IQ quota met.",
  "23028,snarky,%s added. Try fewer experimental pulls.",
  "23028,snarky,%s loaded. No refund for poor life choices.",
  "23028,snarky,%s locked in. Don’t go genius on wrong targets.",
  "23028,snarky,%s engaged. Patch your UI, not the boss.",
  "23028,snarky,%s sealed. Resist ‘yeet pull’ temptations.",
  "23028,snarky,%s active. Less chatter, more shatter.",
  "23028,snarky,%s: fewer pugsplains, more executes.",
  "23028,snarky,%s online. If wipe, consult personal logs.",
  "23028,snarky,%s spun up. Don’t invent new mechanics.",
  "23028,snarky,%s establishes raid brain; use it.",

  "23028,spicy,%s deployed; genius unlocked, chaos probable.",
  "23028,spicy,%s floods the group. Try not to outsmart the plan.",
  "23028,spicy,%s surges. Big braining commences.",
  "23028,spicy,%s ignites our cortexes. Strategize wildly.",
  "23028,spicy,%s saturates the raid. Synaptic thunder.",
  "23028,spicy,%s storms in. Chain ideas responsibly.",
  "23028,spicy,%s lights the hive mind. Buzz louder.",
  "23028,spicy,%s detonates. Tactical enlightenment.",
  "23028,spicy,%s tempers genius with mischief.",
  "23028,spicy,%s dials our brains to eleven.",
  "23028,spicy,%s sparks fireworks in our heads.",
  "23028,spicy,%s declares think-fast or wipe-fast.",
  "23028,spicy,%s lands. Try not to reinvent physics mid-fight.",
  "23028,spicy,%s blasts us with clever. Don’t get cocky.",
  "23028,spicy,%s threads brilliant chaos through us all.",
  "23028,spicy,%s installs shared inspiration. Warranty void.",
  "23028,spicy,%s rings the bell of invention.",
  "23028,spicy,%s pours rocket fuel into the raid brain.",
  "23028,spicy,%s cooks up galaxy brain soup.",
  "23028,spicy,%s unlocks collective overthink mode.",
  "23028,spicy,%s beams a TED talk into our skulls.",
  "23028,spicy,%s gives us ideas faster than strats.",
  "23028,spicy,%s might awaken our inner theorist.",
  "23028,spicy,%s boots creative danger mode.",

  -- Amplify Magic (1008) – 25 each
  "1008,neutral,%s on %t. Heals feel stronger.",
  "1008,neutral,%t empowered by %s. Throughput climbs.",
  "1008,neutral,%s amplifies effects on %t.",
  "1008,neutral,%s heightens the magic around %t.",
  "1008,neutral,%s granted to %t. Numbers go up.",
  "1008,neutral,%s tuned on %t. Friendly spells surge.",
  "1008,neutral,%s: support power rising for %t.",
  "1008,neutral,%s boosts incoming healing for %t.",
  "1008,neutral,%s magnifies helpful magic on %t.",
  "1008,neutral,%s on %t. Enjoy the glow.",
  "1008,neutral,%s strengthens benign effects for %t.",
  "1008,neutral,%s aura wraps %t. Buffs feel buffier.",
  "1008,neutral,%s hums softly around %t.",
  "1008,neutral,%s inclines fortune toward %t.",
  "1008,neutral,%s accentuates the positives for %t.",
  "1008,neutral,%s: brighter numbers in your future, %t.",
  "1008,neutral,%s ramps the friendly vibes for %t.",
  "1008,neutral,%s channels luck and love to %t.",
  "1008,neutral,%s blesses %t with extra oomph.",
  "1008,neutral,%s fine-tunes aid for %t.",
  "1008,neutral,%s coaxes crits toward %t.",
  "1008,neutral,%s invites bigger greens for %t.",
  "1008,neutral,%s primes %t for supportive magic.",
  "1008,neutral,%s turns the dial up for %t.",
  "1008,neutral,%s helps every helpful thing help harder.",

  "1008,snarky,%t with %s—danger requested.",
  "1008,snarky,%s for %t. If you pull aggro, that’s a you problem.",
  "1008,snarky,%t, %s enabled. Healers taking notes.",
  "1008,snarky,%s toggled. Try resisting floor DPS, %t.",
  "1008,snarky,%t, %s is not ‘pull more’ permission.",
  "1008,snarky,%s for %t. Handle your threat.",
  "1008,snarky,%t, %s increases numbers, not IQ.",
  "1008,snarky,%s applied. Healers get the survey later, %t.",
  "1008,snarky,%t, %s means play smarter, not riskier.",
  "1008,snarky,%s active. Try not to flex on boss mechanics, %t.",
  "1008,snarky,%t, %s won’t save you from cleave.",
  "1008,snarky,%s: spicy sauce for healers; don’t chug, %t.",
  "1008,snarky,%t, %s adds sparkle, not invulnerability.",
  "1008,snarky,%s humming. Your life bar is not a dare, %t.",
  "1008,snarky,%t, %s will be on the post-mortem.",
  "1008,snarky,%s blessing delivered. Try subtlety, %t.",
  "1008,snarky,%t, %s plus hubris equals release spirit.",
  "1008,snarky,%s toggled. Threat tables still exist, %t.",
  "1008,snarky,%t, %s isn’t a ‘go pull a pack’ button.",
  "1008,snarky,%s here. Please don’t make content harder, %t.",
  "1008,snarky,%t, %s grants confidence, not immunity.",
  "1008,snarky,%s won’t protect against standing in swirlies, %t.",
  "1008,snarky,%t, %s highlights mistakes in 4K.",
  "1008,snarky,%s on %t. Proceed with adult supervision.",
  "1008,snarky,%t, %s is a buff, not insurance.",

  "1008,spicy,%s: taps to torrents. Try not to drown, %t.",
  "1008,spicy,%t tuned with %s. Spicy numbers ahead.",
  "1008,spicy,%s cranks the sauce on %t.",
  "1008,spicy,%t basking in %s—glow up.",
  "1008,spicy,%s pours accelerant on %t’s positives.",
  "1008,spicy,%t, %s makes the good stuff explode.",
  "1008,spicy,%s dials the buff-o-meter to eleven for %t.",
  "1008,spicy,%t under %s—peak spice.",
  "1008,spicy,%s turns the taps to torrent for %t.",
  "1008,spicy,%t’s aura goes supernova with %s.",
  "1008,spicy,%s infuses %t with supercharge fizz.",
  "1008,spicy,%t dons %s: safety third.",
  "1008,spicy,%s + %t = healer content.",
  "1008,spicy,%t, %s turns green numbers into emeralds.",
  "1008,spicy,%s on %t. The hype is real.",
  "1008,spicy,%t splashed by %s. Make it count.",
  "1008,spicy,%s bathes %t in turbo vibes.",
  "1008,spicy,%t mainlines %s. Live deliciously.",
  "1008,spicy,%s makes %t’s buffs hit like crits.",
  "1008,spicy,%t becomes a highlight reel under %s.",
  "1008,spicy,%s pours rocket fuel into %t’s buffs.",
  "1008,spicy,%t marinates in %s. Zesty.",
  "1008,spicy,%s blesses %t with unhinged positivity.",
  "1008,spicy,%t feels the lift-off from %s.",

  -- Dampen Magic (604) – 25 each
  "604,neutral,%s on %t. Pain reduced.",
  "604,neutral,%t buffered with %s. Impact softened.",
  "604,neutral,%s cushions incoming spikes for %t.",
  "604,neutral,%s tempers harsh magic on %t.",
  "604,neutral,%s eases damage patterns for %t.",
  "604,neutral,%s adds padding to %t’s day.",
  "604,neutral,%s hushes the hurt around %t.",
  "604,neutral,%s mutes incoming sting for %t.",
  "604,neutral,%s tones down volatility on %t.",
  "604,neutral,%s smooths the ride for %t.",
  "604,neutral,%s muffles unfriendly magic for %t.",
  "604,neutral,%s sands the edges off pain for %t.",
  "604,neutral,%s tamps down turbulence for %t.",
  "604,neutral,%s is a pillow for %t’s misadventures.",
  "604,neutral,%s reduces sharp corners life throws at %t.",
  "604,neutral,%s blunts the blow for %t.",
  "604,neutral,%s calms the chaos around %t.",
  "604,neutral,%s tones down the drama for %t.",
  "604,neutral,%s is soft power for %t.",
  "604,neutral,%s dials back the ouch for %t.",
  "604,neutral,%s adds padding to every hit on %t.",
  "604,neutral,%s whispers ‘not today’ to pain for %t.",
  "604,neutral,%s reduces the punch of stray magic on %t.",
  "604,neutral,%s makes bad luck less bad for %t.",
  "604,neutral,%s says: easy there, world, to %t.",

  "604,snarky,%s for %t. Anti-ouch tech engaged.",
  "604,snarky,%t, %s—because the floor keeps critting you.",
  "604,snarky,%s installed. Try fewer avoidable hits, %t.",
  "604,snarky,%t, %s doesn’t block lava.",
  "604,snarky,%s applied. Floors remain undefeated, %t.",
  "604,snarky,%t, %s reduces pain—but not mistakes.",
  "604,snarky,%s muffles pain. Your curiosity causes the rest, %t.",
  "604,snarky,%t, %s can’t nerf greed.",
  "604,snarky,%s shields your ego, barely, %t.",
  "604,snarky,%t, %s eases hits; mechanics still apply.",
  "604,snarky,%s adds bubble wrap, not common sense, %t.",
  "604,snarky,%t, %s reduces drama, not DPS.",
  "604,snarky,%s guards you from oops. Try fewer oops, %t.",
  "604,snarky,%t, %s: because healers are tired.",
  "604,snarky,%s dims pain; don’t test physics, %t.",
  "604,snarky,%t, %s won’t stop boss hugs.",
  "604,snarky,%s backstops your bravery, %t.",
  "604,snarky,%t, %s supports, you still dodge.",
  "604,snarky,%s may reduce your need for band-aids, %t.",
  "604,snarky,%t, %s is not a license to facetank.",
  "604,snarky,%s reduces ouch; you reduce baiting cleaves, %t.",
  "604,snarky,%t, %s doesn’t parry stupidity.",
  "604,snarky,%s: fewer emergency snacks needed, %t.",
  "604,snarky,%t, %s is training wheels, not NOS.",
  "604,snarky,%s is damage control for %t’s impulses.",

  "604,spicy,%s: soft power for reckless hearts like %t.",
  "604,spicy,%t wears %s. Chaos gets a cushion.",
  "604,spicy,%s wraps %t in plush anti-ouch.",
  "604,spicy,%t, %s is your bubble wrap.",
  "604,spicy,%s lines %t’s day with foam padding.",
  "604,spicy,%t walks safer under %s.",
  "604,spicy,%s turns hits into nudges for %t.",
  "604,spicy,%t, %s comforts your inner YOLO.",
  "604,spicy,%s hushes the punch headed for %t.",
  "604,spicy,%t wades through nonsense cushioned by %s.",
  "604,spicy,%s is %t’s personal shock absorber.",
  "604,spicy,%t, %s makes danger feel polite.",
  "604,spicy,%s helps %t glide through bumpier moments.",
  "604,spicy,%t’s M.O.: leap first, add %s.",
  "604,spicy,%s lets %t live to learn later.",
  "604,spicy,%t wrapped in %s. Proceed to giggle.",
  "604,spicy,%s—because %t is apparently a magnet for chaos.",
  "604,spicy,%t smirks at pain under %s.",
  "604,spicy,%s makes calamity less spicy for %t.",
  "604,spicy,%t armors vibes with %s.",
  "604,spicy,%s turns ‘ow’ into ‘eh’ for %t.",
  "604,spicy,%t chooses violence; %s chooses cushion.",
  "604,spicy,%s: polite decline to suffering for %t.",
  "604,spicy,%t rides chaos like a cloud under %s.",
}


