-- Author: Ozy

-- One line per entry: "spellID,category,phrase"
-- Categories: neutral|snarky|spicy (or n|s|sp)

OZY_PRIEST_LINES_VERSION = 1
OZY_PRIEST_LINES = OZY_PRIEST_LINES or {
  -- Power Word: Fortitude (1243) – 25 per category
  "1243,neutral,%t fortified with %s. Be sturdy.",
  "1243,neutral,%s applied. Hit harder, fall less.",
  "1243,neutral,%t receives %s. Bones reinforced.",
  "1243,neutral,%s on %t. Stand tall.",
  "1243,neutral,%s binds resilience to %t.",
  "1243,neutral,%t, %s will keep you on your feet.",
  "1243,neutral,%s strengthens the spirit and sinew of %t.",
  "1243,neutral,%s empowers %t to weather the storm.",
  "1243,neutral,%s on %t. Stamina rising.",
  "1243,neutral,%t steadied by %s.",
  "1243,neutral,%s grants resolve to %t.",
  "1243,neutral,%t, accept %s and endure.",
  "1243,neutral,%s settles upon %t like a shield.",
  "1243,neutral,%s is the quiet courage in %t’s chest.",
  "1243,neutral,%t is tempered by %s.",
  "1243,neutral,%s bolsters %t against the coming blows.",
  "1243,neutral,%t’s frame is braced by %s.",
  "1243,neutral,%s: a calm pillar within %t.",
  "1243,neutral,%t’s footing is firm under %s.",
  "1243,neutral,%s binds grit to %t’s bones.",
  "1243,neutral,%t, bear %s and carry on.",
  "1243,neutral,%s settles %t’s breath and stance.",
  "1243,neutral,%s girds %t against misfortune.",
  "1243,neutral,%t is readied by %s.",
  "1243,neutral,%s steadies %t’s heartbeat and hand.",

  "1243,snarky,%s on %t. Please stop hugging cleaves.",
  "1243,snarky,%t, %s is armor against bad decisions.",
  "1243,snarky,%s delivered. Floors aren’t soft, %t.",
  "1243,snarky,%t, %s will not tank for you.",
  "1243,snarky,%s applied. Try not to test it immediately, %t.",
  "1243,snarky,%t, %s helps; ignoring mechanics doesn’t.",
  "1243,snarky,%s for %t. The boss is not a hug.",
  "1243,snarky,%t, %s won’t stop blender beams.",
  "1243,snarky,%s set. Maybe less scenic cleaving, %t.",
  "1243,snarky,%t, %s reduces damage, not hubris.",
  "1243,snarky,%s assists %t. Gravity still wins.",
  "1243,snarky,%t, %s is not a license to facetank.",
  "1243,snarky,%s: softens hits, not consequences, %t.",
  "1243,snarky,%t, %s won’t fix standing in front.",
  "1243,snarky,%s wrapped. Try not to find a new way to die, %t.",
  "1243,snarky,%t, %s is your seatbelt; click it, don’t test it.",
  "1243,snarky,%s applied. Healer not included, %t.",
  "1243,snarky,%t, %s helps bones; use brain too.",
  "1243,snarky,%s loaded. No more pancake RP, %t.",
  "1243,snarky,%t, %s shields you from physics lightly.",
  "1243,snarky,%s on %t. Keep your ankles away from cleave.",
  "1243,snarky,%t, %s is a buff, not a strategy.",
  "1243,snarky,%s engaged. Please dodge things, %t.",
  "1243,snarky,%t, %s won’t survive your curiosity.",
  "1243,snarky,%s affirmed. Try the back of the boss, %t.",

  "1243,spicy,%s: brick mode engaged for %t.",
  "1243,spicy,%t armors up under %s. Bonk boldly.",
  "1243,spicy,%s packs steel into %t’s stride.",
  "1243,spicy,%t becomes a wall with %s.",
  "1243,spicy,%s snaps into place. %t turns granite.",
  "1243,spicy,%t, %s turns bumps to shrugs.",
  "1243,spicy,%s puts iron in %t’s veins.",
  "1243,spicy,%t steps heavier with %s. The floor feels it.",
  "1243,spicy,%s crowns %t champion of not-dying.",
  "1243,spicy,%t bears %s and grins at danger.",
  "1243,spicy,%s brands resilience across %t’s chest.",
  "1243,spicy,%t, %s laughs at stray pokes.",
  "1243,spicy,%s hardens %t’s will and hide.",
  "1243,spicy,%t wears %s like a fortress.",
  "1243,spicy,%s turns %t’s HP bar into a stubborn line.",
  "1243,spicy,%t strides into chaos under %s.",
  "1243,spicy,%s raises %t’s keep walls higher.",
  "1243,spicy,%t, %s gifts you the vibe: unbreakable.",
  "1243,spicy,%s makes %t allergic to flinching.",
  "1243,spicy,%t marches on; %s carries the bruise bill.",
  "1243,spicy,%s anchors %t to this plane out of spite.",
  "1243,spicy,%t’s hitpoints square their shoulders with %s.",
  "1243,spicy,%s seals %t in plot armor. Almost.",
  "1243,spicy,%t gains main-character sturdiness via %s.",
  "1243,spicy,%s upgrades %t’s ribcage to premium.",

  -- Prayer of Fortitude (21562) – 25 per category
  "21562,neutral,Group fortified: %s active.",
  "21562,neutral,%s spreads resolve across the group.",
  "21562,neutral,%s steadies every stance here.",
  "21562,neutral,%s wraps the raid in resilience.",
  "21562,neutral,%s braces the team for impact.",
  "21562,neutral,%s sounds the call to endure together.",
  "21562,neutral,%s turns wobbles into footholds.",
  "21562,neutral,%s plants our banner and our feet.",
  "21562,neutral,%s makes our health bars less shy.",
  "21562,neutral,%s lifts the group’s backbone.",
  "21562,neutral,%s: fewer flops, more clout.",
  "21562,neutral,%s settles the team’s breath.",
  "21562,neutral,%s thickens our skin where it counts.",
  "21562,neutral,%s grants communal grit.",
  "21562,neutral,%s knits a safety net under all of us.",
  "21562,neutral,%s steadies the raid’s footing.",
  "21562,neutral,%s makes the floor less attractive.",
  "21562,neutral,%s is group spine day.",
  "21562,neutral,%s pours steel into the roster.",
  "21562,neutral,%s pads the sharp edges of fate.",
  "21562,neutral,%s stands between us and the oof.",
  "21562,neutral,%s clears the air of panic.",
  "21562,neutral,%s steadies hands and hearts.",
  "21562,neutral,%s brings collective steadiness online.",
  "21562,neutral,%s supplies raid-wide sturdiness.",

  "21562,snarky,%s: donate threat to the tank, not the floor.",
  "21562,snarky,%s cast. Health bars are not decor.",
  "21562,snarky,%s uploaded. Pancake roleplay canceled.",
  "21562,snarky,%s is up. Cleaves still cleave.",
  "21562,snarky,%s on raid. Please don’t beta-test pain.",
  "21562,snarky,%s engaged. Release spirit is not a strategy.",
  "21562,snarky,%s toggled. Personal space from aoe advised.",
  "21562,snarky,%s online. Gravity still undefeated.",
  "21562,snarky,%s humming. Try fewer experimental pulls.",
  "21562,snarky,%s: less screaming, more beaming.",
  "21562,snarky,%s links the squad. Now link your eyes to the floor.",
  "21562,snarky,%s stabilized. Boss won’t care about excuses.",
  "21562,snarky,%s won’t stop lava from being lava.",
  "21562,snarky,%s grants extra chances; don’t spend them.",
  "21562,snarky,%s active. Try not to invent mechanics.",
  "21562,snarky,%s installed. Don’t put it under QA, team.",
  "21562,snarky,%s set. Less yikes, more smites.",
  "21562,snarky,%s online. Invoke your inner survival, not inner tourist.",
  "21562,snarky,%s running. Keep your hitboxes modest.",
  "21562,snarky,%s present. Stupidity remains physical.",
  "21562,snarky,%s shielded us. Don’t pull with your face.",
  "21562,snarky,%s up. Now stop being allergic to the back of mobs.",
  "21562,snarky,%s buffed. If we wipe, check your legs.",
  "21562,snarky,%s primed. Read mechanics with your eyes, not your soul.",
  "21562,snarky,%s achieved. Heroism now: not dying.",

  "21562,spicy,%s spread. Bulwark vibes only.",
  "21562,spicy,%s pours fortress into our bones.",
  "21562,spicy,%s for the raid. Bruises bounce.",
  "21562,spicy,%s seals our pact with staying upright.",
  "21562,spicy,%s makes us the wall that walks.",
  "21562,spicy,%s lays a stone road under our feet.",
  "21562,spicy,%s hardens our resolve to legendary.",
  "21562,spicy,%s tunes us for stubborn survival.",
  "21562,spicy,%s crowns the raid with endurance.",
  "21562,spicy,%s distills grit into a group aura.",
  "21562,spicy,%s turns panic into posture.",
  "21562,spicy,%s binds us in a keep of will.",
  "21562,spicy,%s inks a contract with our HP bars.",
  "21562,spicy,%s changes wipe energy into win energy.",
  "21562,spicy,%s convinces fate to go easy.",
  "21562,spicy,%s grants the floor less influence.",
  "21562,spicy,%s tells incoming damage to be nice.",
  "21562,spicy,%s wraps the raid in plot armor.",
  "21562,spicy,%s makes healers’ jobs sparkle.",
  "21562,spicy,%s turns near-misses into stories.",
  "21562,spicy,%s channels the stubborn saint in all of us.",
  "21562,spicy,%s installs backbone 2.0.",
  "21562,spicy,%s upgrades us from fragile to formidable.",
  "21562,spicy,%s baptizes the raid in resilience.",

  -- Divine Spirit (14752) – 25 per category
  "14752,neutral,%s on %t. Mana appreciates this.",
  "14752,neutral,%t empowered with %s. Blue bar happier.",
  "14752,neutral,%s refines %t’s focus and flow.",
  "14752,neutral,%s strengthens %t’s inner rhythm.",
  "14752,neutral,%s sets %t’s casting to a calmer cadence.",
  "14752,neutral,%s whispers patience to %t’s mana.",
  "14752,neutral,%s aligns %t’s spirit to sustain.",
  "14752,neutral,%s grants %t more between-breaths power.",
  "14752,neutral,%s gives %t the quiet that fuels spells.",
  "14752,neutral,%s primes %t’s reserves for longer fights.",
  "14752,neutral,%s guides gentle renewal to %t.",
  "14752,neutral,%s steadies %t’s hands and pool.",
  "14752,neutral,%s calms the waves in %t’s bar.",
  "14752,neutral,%s: efficiency in %t’s bloodstream.",
  "14752,neutral,%s hums in %t like a hymn.",
  "14752,neutral,%s turns stray thoughts into focus for %t.",
  "14752,neutral,%s pours clarity into %t’s next cast.",
  "14752,neutral,%s trims waste from %t’s weave.",
  "14752,neutral,%s is the patient breath before power in %t.",
  "14752,neutral,%s smooths %t’s channeling.",
  "14752,neutral,%s blesses %t with calm persistence.",
  "14752,neutral,%s refills %t in the quiet moments.",
  "14752,neutral,%s leads %t to the long game.",
  "14752,neutral,%s anchors %t’s mind in renewal.",
  "14752,neutral,%s keeps %t’s light burning steady.",

  "14752,snarky,%t, %s—your mana problem is now rotation.",
  "14752,snarky,%s applied. Try spells with syllables, %t.",
  "14752,snarky,%t, %s engaged. Your wand isn’t a lifestyle.",
  "14752,snarky,%s for %t. Stop cosplaying as OOM.",
  "14752,snarky,%t, %s fixes bar, not brain.",
  "14752,snarky,%s online. Consider casting something spicy, %t.",
  "14752,snarky,%t, %s won’t refund miscasts.",
  "14752,snarky,%s tuned. Your regen is not an apology, %t.",
  "14752,snarky,%t, %s enables rotation, not vibes.",
  "14752,snarky,%s uplifts your regen; uplift your uptime, %t.",
  "14752,snarky,%t, %s cannot heal button fear.",
  "14752,snarky,%s installed. Try not to wand-bonk, %t.",
  "14752,snarky,%t, %s helps. Standing idle does not.",
  "14752,snarky,%s whispers efficiency. Listen, %t.",
  "14752,snarky,%t, %s isn’t a license to spam heal wrong.",
  "14752,snarky,%s running. Please stop panicking, %t.",
  "14752,snarky,%t, %s won’t fix casting from max range always.",
  "14752,snarky,%s primed. Bars blue; excuses thin, %t.",
  "14752,snarky,%t, %s empowers you to do the rotation.",
  "14752,snarky,%s on %t. Try fewer sips, more smites.",
  "14752,snarky,%t, %s isn’t a pass to overheal.",
  "14752,snarky,%s helps your blue bar, not your red flags, %t.",
  "14752,snarky,%t, %s unlocks spellbook page 2.",
  "14752,snarky,%s loaded. Time to press more than one key, %t.",
  "14752,snarky,%t, %s reminds you: cast wisely.",

  "14752,spicy,%t receives %s. Spiritually swole.",
  "14752,spicy,%s lifts %t’s soul and sustain.",
  "14752,spicy,%t glows with %s. Keep that rhythm.",
  "14752,spicy,%s pours patience into %t’s weave.",
  "14752,spicy,%t under %s: calm and loaded.",
  "14752,spicy,%s makes %t’s mana behave.",
  "14752,spicy,%t’s cadence blooms beneath %s.",
  "14752,spicy,%s stretches %t’s casting budget.",
  "14752,spicy,%t hums with %s. Sustain is a superpower.",
  "14752,spicy,%s teaches %t to breathe between miracles.",
  "14752,spicy,%t steadies under %s, long game unlocked.",
  "14752,spicy,%s puts a metronome in %t’s fingers.",
  "14752,spicy,%t sails farther on %s winds.",
  "14752,spicy,%s primes %t for marathon magic.",
  "14752,spicy,%t’s blue tide rises with %s.",
  "14752,spicy,%s whispers longevity into %t.",
  "14752,spicy,%t keeps the light on with %s.",
  "14752,spicy,%s grows %t’s patience and power.",
  "14752,spicy,%t channels endless with %s.",
  "14752,spicy,%s gives %t unhurried precision.",
  "14752,spicy,%t blooms in endurance under %s.",
  "14752,spicy,%s sets %t’s soul to steady burn.",
  "14752,spicy,%t’s regen sings a hymn under %s.",
  "14752,spicy,%s is quiet heroism for %t’s bars.",

  -- Prayer of Spirit (27681) – 25 per category
  "27681,neutral,%s flows through the group. Blue bars purr.",
  "27681,neutral,%s spreads calm focus across the raid.",
  "27681,neutral,%s teaches patience to all of us.",
  "27681,neutral,%s smooths rotations raid-wide.",
  "27681,neutral,%s shares a steady hand with the team.",
  "27681,neutral,%s brings long-breath casting to the group.",
  "27681,neutral,%s keeps everyone’s lights on.",
  "27681,neutral,%s sets a cadence for the raid’s magic.",
  "27681,neutral,%s turns chaos into measured flow.",
  "27681,neutral,%s tunes the group to sustainable pace.",
  "27681,neutral,%s lifts the baseline of focus.",
  "27681,neutral,%s stitches patience into our play.",
  "27681,neutral,%s makes the long fight feel shorter.",
  "27681,neutral,%s puts a little hush in every cast.",
  "27681,neutral,%s slackens panic across the roster.",
  "27681,neutral,%s raises the ceiling on team composure.",
  "27681,neutral,%s is group wisdom bottled.",
  "27681,neutral,%s refills morale and mana alike.",
  "27681,neutral,%s draws us all into an even rhythm.",
  "27681,neutral,%s tucks extra blue into everyone’s corners.",
  "27681,neutral,%s keeps our engine humming.",
  "27681,neutral,%s is the chorus that carries us.",
  "27681,neutral,%s pours quiet confidence into the raid.",
  "27681,neutral,%s fuels us between miracles.",
  "27681,neutral,%s lays a runway for longer flights.",

  "27681,snarky,%s online. Second thoughts now enabled.",
  "27681,snarky,%s applied. If you go OOM, it’s on you.",
  "27681,snarky,%s humming. Bad rotations now obvious.",
  "27681,snarky,%s active. Fewer wand phases, team.",
  "27681,snarky,%s engaged. Consider reading your talents.",
  "27681,snarky,%s running. Try not to heal the floor.",
  "27681,snarky,%s stabilizes regen; stabilize your plan.",
  "27681,snarky,%s spreads patience. Spread awareness too.",
  "27681,snarky,%s gives you time; don’t waste it.",
  "27681,snarky,%s loaded. Stop panic-casting gray spells.",
  "27681,snarky,%s is not permission to stand still.",
  "27681,snarky,%s widens buffer; not your ego.",
  "27681,snarky,%s supports you; support your hotkeys.",
  "27681,snarky,%s grants a window to think. Use it.",
  "27681,snarky,%s here. Try fewer AFK mind-wanders.",
  "27681,snarky,%s uplifted everyone. Read the room and the boss.",
  "27681,snarky,%s reduces your excuses by 25%.",
  "27681,snarky,%s fuels you. Maybe fuel the strat notes.",
  "27681,snarky,%s assists regen; you assist mechanics.",
  "27681,snarky,%s is group wisdom; don’t argue with it.",
  "27681,snarky,%s installed. Overhealing still a crime.",
  "27681,snarky,%s improves patience; not queue times.",
  "27681,snarky,%s is the calm. You be the competence.",
  "27681,snarky,%s lets you breathe. Don’t sigh, act.",

  "27681,spicy,%s shared. Enlightenment for everyone.",
  "27681,spicy,%s knits a choir of calm through the raid.",
  "27681,spicy,%s sets the long game to song.",
  "27681,spicy,%s lays a river of blue under our feet.",
  "27681,spicy,%s makes miracles pace themselves.",
  "27681,spicy,%s lengthens our reach without rushing.",
  "27681,spicy,%s auras us with sustainable wonder.",
  "27681,spicy,%s gifts the raid the power to wait.",
  "27681,spicy,%s stitches even breath into many chests.",
  "27681,spicy,%s turns chaotic churn into cadence.",
  "27681,spicy,%s braids patience into our spells.",
  "27681,spicy,%s tunes the chorus to endurance.",
  "27681,spicy,%s raises quiet banners in us all.",
  "27681,spicy,%s draws a circle where panic quiets.",
  "27681,spicy,%s teaches the raid the art of enough.",
  "27681,spicy,%s waters the roots of our will.",
  "27681,spicy,%s turns scrambles into sustained push.",
  "27681,spicy,%s writes patience into our muscle memory.",
  "27681,spicy,%s blesses us with the strength to pace.",
  "27681,spicy,%s makes all our small renewals add up.",
  "27681,spicy,%s sets a steady star to steer by.",
  "27681,spicy,%s gives our focus a place to rest.",
  "27681,spicy,%s wraps the team in lasting calm.",
  "27681,spicy,%s turns minutes into a movement.",

  -- Shadow Protection (976) – 25 per category
  "976,neutral,%s on %t. Shadow, begone.",
  "976,neutral,%t warded by %s. Spooky-proofed.",
  "976,neutral,%s shields %t from gloom.",
  "976,neutral,%s dims the reach of the void around %t.",
  "976,neutral,%s narrows shadows seeking %t.",
  "976,neutral,%s holds the line between %t and the shade.",
  "976,neutral,%s is a lantern at %t’s back.",
  "976,neutral,%t, %s turns whispers into wind.",
  "976,neutral,%s wraps %t in warded light.",
  "976,neutral,%s cools the breath of the dark on %t.",
  "976,neutral,%s quiets the void’s appetite for %t.",
  "976,neutral,%s seats courage atop %t’s shadow.",
  "976,neutral,%t’s edges are bright under %s.",
  "976,neutral,%s trims the night’s claws near %t.",
  "976,neutral,%s is the prayer that shadows fear for %t.",
  "976,neutral,%t, %s keeps the unseen at arm’s length.",
  "976,neutral,%s draws a circle of light around %t.",
  "976,neutral,%s makes %t less interesting to the void.",
  "976,neutral,%s slicks the dark’s grip on %t.",
  "976,neutral,%t walks brighter under %s.",
  "976,neutral,%s tastes the air and bars the chill from %t.",
  "976,neutral,%s keeps the gloom’s teeth off %t.",
  "976,neutral,%s puts a visor on %t’s soul.",
  "976,neutral,%s holds fast when the dark leans.",
  "976,neutral,%s teaches shadows manners around %t.",

  "976,snarky,%s for %t. Edgy damage reduced.",
  "976,snarky,%t, %s—brooding down 80%.",
  "976,snarky,%s online. Mysterious orbs less persuasive, %t.",
  "976,snarky,%t, %s won’t stop you from walking into void zones.",
  "976,snarky,%s applied. Emo boss mechanics dislike you, %t.",
  "976,snarky,%t, %s only blocks shadow, not impatience.",
  "976,snarky,%s says no to spooky. You say no to swirlies, %t.",
  "976,snarky,%t, %s won’t cure dramatic timing.",
  "976,snarky,%s deflects whispers; ignore them anyway, %t.",
  "976,snarky,%t, %s will not excuse facepulls.",
  "976,snarky,%s keeps you from being moody bait, %t.",
  "976,snarky,%t, %s is not anti-derp tech.",
  "976,snarky,%s stiff-arms spooky; you stiff-arm baited pulls, %t.",
  "976,snarky,%t, %s cannot tank shadebolts if you try.",
  "976,snarky,%s resists shadow; resist overconfidence, %t.",
  "976,snarky,%t, %s keeps vibes out, not responsibilities.",
  "976,snarky,%s mutes the edgy. Mute your mic when chewing, %t.",
  "976,snarky,%t, %s blocks gloom; don’t block the view.",
  "976,snarky,%s shushes the void; you hush your inner lemming, %t.",
  "976,snarky,%t, %s isn’t a permit to afk in beams.",
  "976,snarky,%s reduces the emo; you reduce the drama, %t.",
  "976,snarky,%t, %s won’t heal your shadowflame romance.",
  "976,snarky,%s helps; still dodge ghosts, %t.",
  "976,snarky,%t, %s prevents gloom, not gloomposting.",

  "976,spicy,%s: emo damage mitigated for %t.",
  "976,spicy,%s drapes a lit cloak over %t.",
  "976,spicy,%t walks where night hesitates under %s.",
  "976,spicy,%s steels %t against the void’s bite.",
  "976,spicy,%t’s outline glows with %s.",
  "976,spicy,%s teaches the dark to keep its distance from %t.",
  "976,spicy,%t under %s: unruffled by whispers.",
  "976,spicy,%s huts the shadow wind for %t.",
  "976,spicy,%t’s spirit wears sunglasses under %s.",
  "976,spicy,%s lets %t stroll through spooky like it’s fog.",
  "976,spicy,%t glints with warded edges under %s.",
  "976,spicy,%s is %t’s ‘no thanks’ to the void.",
  "976,spicy,%t’s aura says not today to darkness with %s.",
  "976,spicy,%s turns night’s claws into dull rubber for %t.",
  "976,spicy,%t keeps the vibe, loses the damage with %s.",
  "976,spicy,%s puts a nightlight in %t’s soul.",
  "976,spicy,%t gains the shade-resistant mood via %s.",
  "976,spicy,%s turns eldritch bite into eldritch breeze for %t.",
  "976,spicy,%t shines anti-spook under %s.",
  "976,spicy,%s invites courage to stand with %t.",
  "976,spicy,%t wears %s like quiet thunder.",
  "976,spicy,%s is the ward in %t’s shadow.",
  "976,spicy,%t keeps ghosts at a polite distance with %s.",
  "976,spicy,%s makes %t’s outline a warning to the dark.",
  "976,spicy,%t, %s says boo back.",

  -- Prayer of Shadow Protection (27683) – 25 per category
  "27683,neutral,%s covers the group. Darkness canceled.",
  "27683,neutral,%s throws a lantern over the raid.",
  "27683,neutral,%s draws bright circles under all of us.",
  "27683,neutral,%s shortens the reach of night across the team.",
  "27683,neutral,%s persuades the gloom to keep its distance.",
  "27683,neutral,%s turns whispers at the raid into weather.",
  "27683,neutral,%s makes shadows trip over our light.",
  "27683,neutral,%s hangs stars in the rafters for us.",
  "27683,neutral,%s thickens courage in every chest here.",
  "27683,neutral,%s cools the void’s breath on our necks.",
  "27683,neutral,%s steadies eyes when things get dim.",
  "27683,neutral,%s slips hope around the roster.",
  "27683,neutral,%s locks the door to the spooky room.",
  "27683,neutral,%s makes a nightlight of the raid.",
  "27683,neutral,%s cuts twilight out of the air we share.",
  "27683,neutral,%s ties warded ribbon around the group.",
  "27683,neutral,%s writes ‘not today’ on our shadows.",
  "27683,neutral,%s closes a window in the void.",
  "27683,neutral,%s pushes the darkness a step back from us.",
  "27683,neutral,%s is a song the dark won’t sing with us.",
  "27683,neutral,%s makes the raid less edible to night.",
  "27683,neutral,%s keeps the eerie as just ambience.",
  "27683,neutral,%s straightens spines and banishes shivers.",
  "27683,neutral,%s lends the room a safer shade.",
  "27683,neutral,%s replaces dread with focus.",

  "27683,snarky,%s installed. Emo phase postponed.",
  "27683,snarky,%s applied. Mysterious orbs less persuasive now.",
  "27683,snarky,%s up. Edgy RP canceled for tonight.",
  "27683,snarky,%s humming. Try not to romance the void.",
  "27683,snarky,%s cast; the darkness still bites if you hug it.",
  "27683,snarky,%s for all. Please don’t go sightseeing in pools.",
  "27683,snarky,%s won’t fix standing in the cone of despair.",
  "27683,snarky,%s is strong; your curiosity is stronger. Resist.",
  "27683,snarky,%s applied. The void unfollowed us.",
  "27683,snarky,%s running. The boss still signs your death slips.",
  "27683,snarky,%s grants immunity to brooding, not beams.",
  "27683,snarky,%s buffed. Logistics still matter.",
  "27683,snarky,%s tuned. Try less dramatic gasps.",
  "27683,snarky,%s: spooky down, responsibility up.",
  "27683,snarky,%s won’t make void zones friendly circles.",
  "27683,snarky,%s done. Don’t RP as bait.",
  "27683,snarky,%s hushes whispers. Hush your lemming urges.",
  "27683,snarky,%s blocks cosmic angst; you block frontals.",
  "27683,snarky,%s on raid. Emo damage lower, ego not so much.",
  "27683,snarky,%s grants courage; not a license to yolo.",
  "27683,snarky,%s slows the spooky; you speed the kill.",
  "27683,snarky,%s reduces moodiness; fix positioning yourselves.",
  "27683,snarky,%s helps a lot; common sense required.",
  "27683,snarky,%s is anti-void; not anti-derp.",

  "27683,spicy,%s: Anti-void drip equipped.",
  "27683,spicy,%s unfurls a canopy of light over us.",
  "27683,spicy,%s braids bright thread through the raid.",
  "27683,spicy,%s melts dread into quiet resolve.",
  "27683,spicy,%s pins star-notes into every aura.",
  "27683,spicy,%s turns the room from haunted to heroic.",
  "27683,spicy,%s weaves a warded quilt for all.",
  "27683,spicy,%s lets us move through shadows like fish through water.",
  "27683,spicy,%s teaches darkness to speak softly to us.",
  "27683,spicy,%s crowns our courage with glow.",
  "27683,spicy,%s bends the night around our intent.",
  "27683,spicy,%s fixes our focus in the starfield.",
  "27683,spicy,%s hangs a sign on us: not for the void.",
  "27683,spicy,%s scrubs the dread out of the air.",
  "27683,spicy,%s puts a hush where fear would be.",
  "27683,spicy,%s scolds the dark until it minds.",
  "27683,spicy,%s makes the raid taste inedible to gloom.",
  "27683,spicy,%s reflects the night’s stare back at it.",
  "27683,spicy,%s sharpens our edges against shadow.",
  "27683,spicy,%s tucks a small dawn into our pockets.",
  "27683,spicy,%s is a bright contract we all sign.",
  "27683,spicy,%s is courage with a soft afterglow.",
  "27683,spicy,%s turns the spooky soundtrack down.",
  "27683,spicy,%s leaves footprints of light when we move.",
}


